# Prometheus configuration for CIFAR-10 API monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting rules files
rule_files:
  - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # CIFAR-10 API metrics
  - job_name: 'cifar10-api'
    static_configs:
      - targets: ['cifar-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Alertmanager monitoring
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093'] 